name: 03 - Actions!
on:
    push:
        branches: "feature/**"
jobs:
    checkout_aspnet_docker:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0'

            # - name: List files in project directory
            #   run: ls -la Fiap.Web.SmartWasteManagement

            - name: Build ASP.NET Core project
              run: dotnet build Fiap.Web.SmartWasteManagement/Fiap.Web.SmartWasteManagement.sln --configuration Release

            - name: Build Docker
              uses: docker/build-push-action@v6
              with: 
                push: false
                
            - name: Executar Scripts
              run: |
                git branch
                dotnet --version
                dotnet clean Fiap.Web.SmartWasteManagement/Fiap.Web.SmartWasteManagement.sln


            