name: 03 - Actions!
on:
    push:
        branches: "feature/**"
jobs:
    checkout_aspnet_docker:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0'
            - name: Restore NuGet packages
              run: dotnet restore
            - name: Build ASP.NET Core project
              run: dotnet build --configuration Release
            - name: Build Docker
              uses: docker/build-push-action@v6
              with: 
                push: false
            - name: Executar Scripts
              run: |
                git branch
                dotnet --version
                dotnet clean